/**
 * Opossum Circuit Breaker & Retry Wrapper for Gemini 2.5 Flash AI Auditing
 */

import CircuitBreaker from "opossum";
import { dlqService } from "./dlq";

export interface GeminiAuditRequest {
  razorpayRecord?: any;
  bankRecord?: any;
  erpRecord?: any;
  exceptionType?: string;
  varianceAmount?: number;
}

export interface GeminiAuditResponse {
  confidence: number;
  reasoning: string;
  recommendedAction: string;
  auditStatus: "SUCCESS" | "AUDIT_PENDING_MANUAL_REVIEW";
}

// Low-level function that performs the Gemini API call with retries
async function performGeminiApiCall(req: GeminiAuditRequest): Promise<GeminiAuditResponse> {
  const maxRetries = 3;
  let lastError: any = null;

  for (let attempt = 1; attempt <= maxRetries; attempt++) {
    try {
      // Simulate or call Gemini API
      const apiKey = process.env.GEMINI_API_KEY;
      
      if (!apiKey || apiKey === "mock") {
        // Deterministic response for mock / missing key mode
        return {
          confidence: 88,
          reasoning: `[Gemini 2.5 Flash Audit] Analyzed UTR and variance ₹${req.varianceAmount || 0}. Settlement delta attributed to timing window or payment gateway fee tier.`,
          recommendedAction: "Approve transaction match; post balancing journal entry.",
          auditStatus: "SUCCESS"
        };
      }

      // If real key exists, import dynamically
      const { GoogleGenAI } = await import("@google/genai");
      const ai = new GoogleGenAI({ apiKey });
      
      const prompt = `You are a Senior Financial Forensic Auditor. Reconcile this payment discrepancy:
Razorpay Record: ${JSON.stringify(req.razorpayRecord || null)}
Bank Statement: ${JSON.stringify(req.bankRecord || null)}
ERP Sales Ledger: ${JSON.stringify(req.erpRecord || null)}
Discrepancy Variance: ₹${req.varianceAmount || 0}

Respond in JSON format with fields:
- confidence (number 0-100)
- reasoning (string explanation)
- recommendedAction (string action item)
`;

      const response = await ai.models.generateContent({
        model: "gemini-2.5-flash",
        contents: prompt
      });

      const text = response.text || "";
      let jsonParsed: any = {};
      try {
        const cleaned = text.replace(/```json/g, "").replace(/```/g, "").trim();
        jsonParsed = JSON.parse(cleaned);
      } catch {
        jsonParsed = {
          confidence: 75,
          reasoning: text.slice(0, 300) || "Gemini audit completed.",
          recommendedAction: "Review variance against settlement statement."
        };
      }

      return {
        confidence: jsonParsed.confidence ?? 80,
        reasoning: jsonParsed.reasoning || "Audit reasoning generated by Gemini 2.5 Flash.",
        recommendedAction: jsonParsed.recommendedAction || "Manual verification recommended.",
        auditStatus: "SUCCESS"
      };
    } catch (err: any) {
      lastError = err;
      console.warn(`[Gemini CircuitBreaker] Attempt ${attempt}/${maxRetries} failed: ${err?.message || err}`);
      if (attempt < maxRetries) {
        // Exponential backoff delay (200ms, 400ms)
        await new Promise((res) => setTimeout(res, attempt * 200));
      }
    }
  }

  throw lastError || new Error("Gemini AI request failed after 3 retries");
}

// Configure Opossum Circuit Breaker Options
const circuitBreakerOptions: CircuitBreaker.Options = {
  timeout: 8000, // 8 second timeout per call
  errorThresholdPercentage: 50, // Open circuit if 50% of requests fail
  resetTimeout: 20000, // Stay open for 20s before testing again
  capacity: 10
};

export const geminiCircuitBreaker = new CircuitBreaker(performGeminiApiCall, circuitBreakerOptions);

// Define fallback handler when circuit breaker trips or retries exhaust
geminiCircuitBreaker.fallback(async (req: GeminiAuditRequest, err?: any): Promise<GeminiAuditResponse> => {
  const errorMessage = err?.message || "Gemini API Timeout or Circuit Breaker Tripped";
  console.error(`[Gemini CircuitBreaker Fallback] Triggered for request: ${errorMessage}`);

  // Enqueue failed item into Redis-backed Dead-Letter Queue (DLQ)
  await dlqService.enqueue({
    transactionId: req.razorpayRecord?.paymentId || req.bankRecord?.bankRef || "UNKNOWN_TX",
    paymentId: req.razorpayRecord?.paymentId,
    orderId: req.razorpayRecord?.orderId || req.erpRecord?.orderId,
    reason: "AUDIT_PENDING_MANUAL_REVIEW: Gemini AI service unavailable or rate limited",
    errorDetail: errorMessage,
    payload: req,
    maxRetries: 3
  });

  return {
    confidence: 0,
    reasoning: `[AUDIT_PENDING_MANUAL_REVIEW] AI Circuit Breaker active (${errorMessage}). Record queued in Dead-Letter Queue (DLQ) for auditor review.`,
    recommendedAction: "Flagged for manual auditor review via DLQ dashboard.",
    auditStatus: "AUDIT_PENDING_MANUAL_REVIEW"
  };
});

geminiCircuitBreaker.on("open", () => {
  console.warn("⚠️ [Circuit Breaker] Gemini AI Circuit OPENED - Requests will route directly to DLQ.");
});

geminiCircuitBreaker.on("halfOpen", () => {
  console.log("ℹ️ [Circuit Breaker] Gemini AI Circuit HALF-OPEN - Testing endpoint stability.");
});

geminiCircuitBreaker.on("close", () => {
  console.log("✅ [Circuit Breaker] Gemini AI Circuit CLOSED - Normal operation restored.");
});
